content/posts/0004-dotnet-rearchitecture.md
Fixes a typo, corrects the publish date, and renames the file to follow the existing numbering scheme.
=> Fixes a few typos

assets/scss/main.scss, assets/scss/post.scss, content/posts/0004-writing-buildpacks.md
I've made some copy edits / formatting changes to #8. This PR is based on that one and will modify it when merged.
=> Minor copy edits / formatting to #8

layouts/partials/head.html
Late fix for https://github.com/paketo-buildpacks/blog/pull/18
=> Shareable content

layouts/partials/head.html
https://github.com/paketo-buildpacks/blog/issues/19 iterating on getting this to work.
=> use meta property tag for thumbnail on linkedin

assets/scss/index.scss, assets/scss/main.scss, assets/scss/post.scss, layouts/index.html
- Reworks the link style in order to make it line up with what is on
paketo.io and make the link on the header less intrusive.
Resolves #9
=> Adds link to paketo.io when you click the header

layouts/partials/head.html
=> Adds analytics JS tag

content/posts/0008-introducing-liberty.md
Fixing issue on blog post. 
Before:
After:
=> Fix format issue

content/posts/0009-2021-recap.md
=> Update date on recap

content/posts/0013-oss-health-assessment-1H2022.md
Signed-off-by: David Espejo <daespejo@vmware.com>
Swapping Markdown table for a list
=> Modify blog post

content/posts/0015-oss-contributor-of-the-month.md
Signed-off-by: David Espejo <daespejo@vmware.com>
Add blog post describing the Contributor of the Month initiative
=> Add new post

content/posts/0016-paketo-dev-libraries.md
Attempt to answer the question, which library should I use to write a buildpack?
Provides an explanation of the three different libraries, compares and provides some rough guidelines for selecting a buildpack library.
=> Write a blog post around libcnb/libpak/packit

content/posts/0017-2022-recap.md
=> Adds 2022 recap post

content/posts/0018-2023-roadmap.md
I'd like a  ✅  from @dmikusa before this gets merged.
=> Adds 2023 roadmap post

content/posts/0021-java-buildpacks-enhancements.md
Add blog post describing Java enhancements
Java builds with Maven, Gradle and Spring Boot
=> Add blog post describing Java enhancements

content/posts/0022-bionic-eos.md
blog post about the end of support for bionic in the project
=> Add Bionic end-of-support post

content/posts/0023-paketo-buildpacks-hacktoberfest-2023.md
=> Add blog post for Hacktoberfest 2023

content/posts/0023-paketo-buildpacks-hacktoberfest-2023.md
* [] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
=> Fix Github issue search link

content/posts/0024-bionic-builder-unsafe.md
This PR stages a blog for the potential Bionic Brownout.
https://github.com/orgs/paketo-buildpacks/discussions/224 has been approved, this is ready to be published.
=> Blog for Bionic Brownout

content/posts/0027-ubi-stack-promotion.md
Do Not land until https://github.com/paketo-buildpacks/rfcs/pull/315 is approved and we've moved the stack over.
Share information about moving the ubi stack to
paketo-buildpacks from paketo-community.
Refs: https://github.com/paketo-buildpacks/rfcs/pull/315#discussion_r1940071039
=> doc: add blog post on ubi stack move

content/posts/0028-contributors-wanted.md
=> Post about contributors

content/posts/0029-gcr-sunset.md
=> Add post about GCR sunset

content/posts/0030-paketo-buildpacks-usage-and-socials.md
* where Paketo is being used
* recent interviews and conferences
=> Add a post about:

content/posts/0031-ubi-builders-promotion.md
=> Fix yaml in latest post

content/posts/0032-java-azure-sunset.md
From Java Team RFC 18 -> https://github.com/paketo-buildpacks/rfcs/blob/main/text/java/0018-retire-java-azure-composite.md
=> Add blog post about Java Azure sunset
